
name: 'Package Add-Ons'

on:
    push:
        branches:
            - main

jobs:
    release:
        name: 📦 package
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.1.1
              env:
                  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
            - name: Bedrock Addon Packager
              uses: Fabrimat/addon-packager-action@v0.1
            - name: Github commit and push
              uses: Smart-Transportation/push@v1.3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                message: Publish addons
                branch: packages
