
name: 'Package Add-Ons'

on:
    push:
        branches:
            - main
jobs:
    release:
        name: 📦 package
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.1.1
            - name: Bedrock Addon Packager
              uses: Fabrimat/addon-packager-action@v0.2
            - name: Publish release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "*.mcaddon,*.mcpack,*.zip"
                  bodyFile: "release.md"
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag: "Downloads"
                  name: "Downloads"
                  replacesArtifacts: true
                  removeArtifacts: true
                  allowUpdates: true
            - name: Checkout
              uses: actions/checkout@v2.1.1
              with:
                  ref: packages
                  clean: false
            - name: Github commit and push
              uses: Smart-Transportation/push@v1.3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                message: Publish addons
                branch: packages
